
const ProductData = [
    {
        productImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-02.jpg?v=1706520668",
        productID: 1,
        productTitle: "Color print t-shirt",
        price:1800,
        categories:"cloth",
        reviews:"No reviews",
        qnty:0,
        order:43,
        stock:"41 in stock",
        },
      {
        productImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-03.jpg?v=1707801521",
        productID: 2,
        productTitle: "Leather shoes",
        price:3600,
        categories:"cloth",
        reviews:"3 reviews",
        qnty:0,
        stock:"15 in stock",
        order:35
      },
      {
        productImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-08.jpg?v=1706530972&width=360",
        productID: 3,
        productTitle: "Half sleev tshirt",
        price:1000,
        categories:"cloth",
        reviews:"4 reviews",
        qnty:0,
        stock:"20 in stock",
        order:45,
      },
      {
        productImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-12-d.jpg?v=1706521196&width=360",
        productID: 4,
        productTitle: "Partywear shoes",
        price:1600,
        categories:"cloth",
        reviews:"no reviews",
        qnty:0,
        stock:"10 left",
        order:54,
      },
      {
        productImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-05.jpg?v=1706520582",
        productID: 5,
        productTitle: "Blue heavy t-shirt",
        price:1900,
        categories:"cloth",
        reviews:"2 reviews",
        qnty:0,
        stock:"12 in stock",
        order:37,
      },
      {
        productImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-07_b45fa59b-c020-4410-94ab-42e4c35c0499.jpg?v=1707801524&width=360",
        productID: 6,
        productTitle: "Formal shoes",
        price:2500,
        categories:"cloth",
        reviews:"1 review",
        qnty:0,
        stock:"17 in stock",
        order:54,
      },
      {
        productImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-10_a4c29d52-1206-4ce4-9fee-3195feb0a407.jpg?v=1706520987&width=360",
        productID: 7,
        productTitle: "Formal tshirt",
        price:2000,
        categories:"cloth",
        stock:"16 in stock",
        reviews:'3 review',
        qnty:0,
      },
      {
        productImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-09.jpg?v=1706521373&width=360",
        productID: 8,
        productTitle: "Youngwear shoes",
        price:1900,
        categories:"cloth",
        reviews:"2 reviews",
        stockavail:"19 sold in last 2 hours",
        stock:"15 in stock",
        qnty:0,
        order:27,
     },
      {
        productImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-04.jpg?v=1706520663&width=360",
        productID: 9,
        productTitle: "Bucket hat",
        price:2600,
        categories:"Cap",
        reviews:"",
        stockavail:"10 sold in last 2 hours",
        stock:"12 in stock",
        qnty:0,
        order:55,
     },
      {
        productImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-11-a_5e97d2e1-1158-4e58-886c-8fed88e4d652.jpg?v=1707741296&width=360",
        productID: 10,
        productTitle: "Leather sandals",
        orignalPrice: " ",
        discountPrice: "Rs.2,600.00",
        price:2600,
        categories:"cloth",
        discount: "",
        color1: " ",
        color2: " ",
        color3: " ",
        color4: " ",
        reviews:"3 reviews",
        order:43,
        qnty:0,
        stockavail:"19 sold in last 2 hours",
        stock:"22 in stock",
        description:'Available in Multiple Colors: Choose from a range of sophisticated colors to match your personal style. Whether you prefer classic black, elegant navy, or a vibrant shade to make a statement, we have options to suit every taste.',
        image1:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-11-b_fad89752-b603-4bbb-8826-d6aefca335fe.jpg?v=1707741296&width=120",
        image2:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-11-b_fad89752-b603-4bbb-8826-d6aefca335fe.jpg?v=1707741296&width=120",
        image3:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-11-a_5e97d2e1-1158-4e58-886c-8fed88e4d652.jpg?v=1707741296&width=120",
        image4:"",
        secondaryImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-11-b_fad89752-b603-4bbb-8826-d6aefca335fe.jpg?v=1707741296&width=360",
      },
      {
        productImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-06.jpg?v=1706521040&width=360",
        productID: 11,
        productTitle: "Hat craft",
        orignalPrice: " ",
        discountPrice: "Rs.2,600.00",
        price:2600,
        categories:"Cap",
        discount: "",
        color1: " ",
        color2: " ",
        color3: " ",
        color4: " ",
        reviews:"",
        qnty:0,
        order:34,
        stockavail:"14 sold in last 2 hours",
        stock:"20 in stock",
        description:'Available in Multiple Colors: Choose from a range of sophisticated colors to match your personal style. Whether you prefer classic black, elegant navy, or a vibrant shade to make a statement, we have options to suit every taste.',
        image1:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-06.jpg?v=1706521040&width=120",
        image2:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-06-e.jpg?v=1706521040&width=360",
        image3:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-06-c.jpg?v=1706521040&width=120",
        image4:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-06-b.jpg?v=1706521040&width=120",
        secondaryImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-06-a.jpg?v=1706521040&width=360",
      },
      {
        productImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-01.jpg?v=1707741322&width=360",
        productID: 12,
        productTitle: "Sportwear shoes",
        orignalPrice: " ",
        discountPrice: "Rs.2,600.00",
        price:2600,
        categories:"cloth",
        discount: "",
        color1: " ",
        color2: " ",
        color3: " ",
        color4: " ",
        reviews:"",
        qnty:0,
        order:25,
        sstockavail:"9 sold in last 2 hours",
        stock:"12 in stock",
        description:'Available in Multiple Colors: Choose from a range of sophisticated colors to match your personal style. Whether you prefer classic black, elegant navy, or a vibrant shade to make a statement, we have options to suit every taste.',
        image1:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-01-a.jpg?v=1706521210&width=360",
        image2:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-01-c.jpg?v=1706521210&width=360",
        image3:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-01-b.jpg?v=1706521211&width=120",
        image4:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-01.jpg?v=1707741322&width=120",
        secondaryImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-lyfestyle-product-01-e.jpg?v=1707741322&width=360",
      },
      {
        productImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-09-e.jpg?v=1706521500&width=360",
        productID: 13,
        productTitle: "Doll for pram",
        orignalPrice: " ",
        discountPrice: "Rs.3,600.00",
        price:3600,
        categories:"Accesories",
        discount: "",
        color1: " ",
        color2: " ",
        color3: " ",
        color4: " ",
        reviews:" 1 reviews",
        order:39,
        qnty:0,
        stockavail:"7 sold in last 2 hours",
        stock:"17 in stock",
        description:'Available in Multiple Colors: Choose from a range of sophisticated colors to match your personal style. Whether you prefer classic black, elegant navy, or a vibrant shade to make a statement, we have options to suit every taste.',
        image1:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-09-a.jpg?v=1706521500",
        image2:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-09-b.jpg?v=1706521500&width=360",
        image3:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-09-d.jpg?v=1706521500&width=360",
        image4:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-09.jpg?v=1706521500&width=360",
        secondaryImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-09.jpg?v=1706521500&width=360",
      },
      {
        productImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-04-a_e9cde9f3-5a8d-47c1-bf0d-bce247b84983.jpg?v=1706521562&width=360",
        productID: 14,
        productTitle: "Rattles with wooden",
        orignalPrice: " ",
        discountPrice: "Rs.1,900.00",
        price:1900,
        categories:"Accesories",
        discount: "",
        color1: " ",
        color2: " ",
        color3: " ",
        color4: " ",
        reviews:"",
        qnty:0,
        order:42,
        stockavail:"15 sold in last 2 hours",
        stock:"22 in stock",
        description:'Available in Multiple Colors: Choose from a range of sophisticated colors to match your personal style. Whether you prefer classic black, elegant navy, or a vibrant shade to make a statement, we have options to suit every taste.',
        image1:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-04_69bba67b-3ade-4707-be81-7d34d082692c.jpg?v=1706521562&width=120",
        image2:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-04-e.jpg?v=1706521562&width=120",
        image3:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-04-c_e8309bda-f3b6-4c87-9ff4-253ca8b2292e.jpg?v=1706521562&width=120",
        image4:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-04-a_e9cde9f3-5a8d-47c1-bf0d-bce247b84983.jpg?v=1706521562&width=120",
        secondaryImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-04_69bba67b-3ade-4707-be81-7d34d082692c.jpg?v=1706521562&width=360",
      },
      {
        productImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-07.jpg?v=1706521624&width=360",
        productID: 15,
        productTitle: "Red speed car",
        orignalPrice: " ",
        discountPrice: "Rs.2,600.00",
        price:2600,
        categories:"Accesories",
        discount: "",
        color1: " ",
        color2: " ",
        color3: " ",
        color4: " ",
        reviews:"",
        qnty:0,
        order:30,
        stockavail:"6 sold in last 2 hours",
        stock:"20 in stock",
        description:'Available in Multiple Colors: Choose from a range of sophisticated colors to match your personal style. Whether you prefer classic black, elegant navy, or a vibrant shade to make a statement, we have options to suit every taste.',
        image1:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-07-a.jpg?v=1706521624&width=120",
        image2:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-07-d.jpg?v=1706521610&width=120",
        image3:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-07-b.jpg?v=1706521609&width=120",
        image4:"https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-07-e.jpg?v=1706521624&width=120",
        secondaryImage:
          "https://mb-demo1.myshopify.com/cdn/shop/files/marbo-baby-store-product-07-b.jpg?v=1706521609&width=360",
      },
    ]

export default ProductData;


